---
# Inventario general de dispositivos

all:
  children:

    switches:
      hosts:
        SW_1:
          ansible_host: 192.168.10.11
        SW_2:
          ansible_host: 192.168.10.12
        SW_core:
          ansible_host: 192.168.1.1
        SW_DIST:
          ansible_host: 172.16.1.2

    routers:
      hosts:
        R1:
          ansible_host: 192.168.1.254

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_user: admin
    ansible_password: admin123
